package projeto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;

/**
 *
 * @author ferna
 */
public class QuizForm extends javax.swing.JFrame {

    String[] questions = {"O que significa a sigla SQL?", "Qual declaração devemos usar para efetuar uma consulta a um banco de dados?", "Para excluir um registro único de uma tabela, qual das seguintes declarações pode ser usada?", "Caso você necessite inserir um novo registro no banco de dados, qual declaração deve utilizar?", "Como excluir uma exibição (visão) de nome vw_LivrosAutores?", "Qual das declarações a seguir adiciona uma coluna de nome ID_editora a uma tabela já existente, de nome tbl_livro?", "Qual dos seguintes NÃO é um tipo de join usado em SQL?", "Qual a declaração que devemos utilizar para retornar os dados da coluna NomeCliente da tabela tblClientes?", "Se quisermos atualizar um registro em uma tabela do banco de dados, qual declaração devemos utilizar?", "Precisamos classificar em ordem os resultados obtidos em uma consulta SQL. Qual da seguintes declarações deve ser utilizada para esse fim?"};

    String[][] options = {{"Structured Query Language", "Structured Quiz Language", "Standard Question Language", "Structured Quorum Language", "Structured Query Language"}, {"GET", "CONSULT", "SELECT", "QUERY", "SELECT"}, {"TRUNCATE", "REMOVE", "ERASE", "DELETE", "DELETE"}, {"ADD REGISTER", "INSERT RECORD", "NEW DATA", "INSERT INTO", "INSERT INTO"}, {"DELETE VIEW vw_LivrosAutores", "EXCLUDE VIEW vw_LivrosAutores", "DROP VIEW vw_LivrosAutores", "ERASE VIEW vw_LivrosAutores", "DROP VIEW vw_LivrosAutores"}, {"ALTER TABLE ADD ID_editora tbl_livro SMALLINT NOT NULL;", "CREATE TABLE tbl_livro (ID_editora SMALLINT NOT NULL);", "ALTER TABLE tbl_livro INSERT ID_editora SMALLINT NOT NULL;", "ALTER TABLE tbl_livro ADD ID_editora SMALLINT NOT NULL;", "ALTER TABLE tbl_livro ADD ID_editora SMALLINT NOT NULL;"}, {"IINER JOIN", "OUTER JOIN", "EXTRA JOIN", "CROSS JOIN", "EXTRA JOIN"}, {"SELECT NomeCLiente FROM tblClientes", "RETURN NomeCLiente FROM tblClientes", "SELECT tblClientes FROM NomeCLiente", "GET NomeCLiente BY tblClientes", "SELECT NomeCLiente FROM tblClientes"}, {"MODIFY", "UPDATE", "UPGRADE", "TABLE-SET", "UPDATE"}, {"SORT BY", "ORDENATE", "CLASSIFY BY", "ORDER BY", "ORDER BY"}};
    int index = 0, correct = 0;

    ButtonGroup bg = new ButtonGroup();

    public QuizForm() {
        initComponents();

        bg.add(jRadioButton1_);
        bg.add(jRadioButton2_);
        bg.add(jRadioButton3_);
        bg.add(jRadioButton4_);

        jButton_Next_QActionPerformed(null);
    }

    public void getSelectedOption(JRadioButton rbtn) {
        
        System.out.println(rbtn.getText());
        System.out.println(options[index][4]);
        
        if(rbtn.getText().equals(options[index][4])){
            correct++;
        }
        index++;
        enableRbuttons(false);
    }

    public void enableRbuttons(boolean yes_or_no) {
        jRadioButton1_.setEnabled(yes_or_no);
        jRadioButton2_.setEnabled(yes_or_no);
        jRadioButton3_.setEnabled(yes_or_no);
        jRadioButton4_.setEnabled(yes_or_no);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Questao = new javax.swing.JPanel();
        Lbl_Question = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1_ = new javax.swing.JRadioButton();
        jRadioButton2_ = new javax.swing.JRadioButton();
        jRadioButton3_ = new javax.swing.JRadioButton();
        jRadioButton4_ = new javax.swing.JRadioButton();
        jButton_Next_Q = new javax.swing.JButton();
        jButton_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Questao.setBackground(new java.awt.Color(186, 79, 84));

        Lbl_Question.setBackground(new java.awt.Color(255, 102, 102));
        Lbl_Question.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lbl_Question.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Question.setText("Question");

        javax.swing.GroupLayout jPanel_QuestaoLayout = new javax.swing.GroupLayout(jPanel_Questao);
        jPanel_Questao.setLayout(jPanel_QuestaoLayout);
        jPanel_QuestaoLayout.setHorizontalGroup(
            jPanel_QuestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lbl_Question, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        jPanel_QuestaoLayout.setVerticalGroup(
            jPanel_QuestaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lbl_Question, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jRadioButton1_.setBackground(new java.awt.Color(102, 0, 102));
        jRadioButton1_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1_.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1_.setText("jRadioButton1");
        jRadioButton1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_ActionPerformed(evt);
            }
        });

        jRadioButton2_.setBackground(new java.awt.Color(102, 0, 102));
        jRadioButton2_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2_.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2_.setText("jRadioButton2");
        jRadioButton2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_ActionPerformed(evt);
            }
        });

        jRadioButton3_.setBackground(new java.awt.Color(102, 0, 102));
        jRadioButton3_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3_.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3_.setText("jRadioButton3");
        jRadioButton3_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3_ActionPerformed(evt);
            }
        });

        jRadioButton4_.setBackground(new java.awt.Color(102, 0, 102));
        jRadioButton4_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4_.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4_.setText("jRadioButton4");
        jRadioButton4_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4_ActionPerformed(evt);
            }
        });

        jButton_Next_Q.setBackground(new java.awt.Color(255, 102, 0));
        jButton_Next_Q.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Next_Q.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Next_Q.setText("PRÓXIMA QUESTÃO");
        jButton_Next_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Next_QActionPerformed(evt);
            }
        });

        jButton_Voltar.setBackground(new java.awt.Color(255, 102, 0));
        jButton_Voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Voltar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Voltar.setText("VOLTAR PRO MENU");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton_Next_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1_, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2_, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3_, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4_, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Next_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Questao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Questao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Next_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Next_QActionPerformed

        if(jButton_Next_Q.getText().equals("REINICIE O QUIZ")){
            
            jButton_Next_Q.setText("PRÓXIMA QUESTÃO");
            index = 0;
            correct = 0;
        }
        
        if (index == questions.length) {
            
            Lbl_Question.setText("SEU RESULTADO: " + correct + " / " + questions.length);
            jButton_Next_Q.setText("REINICIE O QUIZ");      
    }//GEN-LAST:event_jButton_Next_QActionPerformed
        else {
            
            enableRbuttons(true);

            Lbl_Question.setText(questions[index]);
            jRadioButton1_.setText(options[index][0]);
            jRadioButton2_.setText(options[index][1]);
            jRadioButton3_.setText(options[index][2]);
            jRadioButton4_.setText(options[index][3]);

            jButton_Next_Q.setText("PRÓXIMO");
        }
        bg.clearSelection();
    }

    private void jRadioButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_ActionPerformed
        getSelectedOption(jRadioButton1_);
    }//GEN-LAST:event_jRadioButton1_ActionPerformed

    private void jRadioButton2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_ActionPerformed
        getSelectedOption(jRadioButton2_);
    }//GEN-LAST:event_jRadioButton2_ActionPerformed

    private void jRadioButton3_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3_ActionPerformed
        getSelectedOption(jRadioButton3_);
    }//GEN-LAST:event_jRadioButton3_ActionPerformed

    private void jRadioButton4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4_ActionPerformed
        getSelectedOption(jRadioButton4_);
    }//GEN-LAST:event_jRadioButton4_ActionPerformed

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        MenuForm mf = new MenuForm();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Question;
    private javax.swing.JButton jButton_Next_Q;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Questao;
    private javax.swing.JRadioButton jRadioButton1_;
    private javax.swing.JRadioButton jRadioButton2_;
    private javax.swing.JRadioButton jRadioButton3_;
    private javax.swing.JRadioButton jRadioButton4_;
    // End of variables declaration//GEN-END:variables
}
